### PR TITLE
Expose constructor for DateFormat to allow construction of custom date formats

### PR DESCRIPTION
**Pull request by timbod7**
I couldn't see any other way to do this.

### CODE REVIEW

**Comment by twittner** [comment]
There is an [`IsString` instance ](https://github.com/twittner/tinylog/blob/develop/src/System/Logger/Settings.hs#L141) for `DateFormat`. Is this not sufficient?

**Comment by timbod7** [comment]
Thanks - yes that is sufficient. 

I wanted this so that I could increase the time resolution of the logs. However, it looks like the existing format string can't support displaying milliseconds... Can you suggest a way do to this?

**Comment by twittner** [comment]
This is a limitation of `strftime`. The most straightforward alternative would be to switch from `unix-time` to `time`. This would allow using `%q` or `%Q` for picosecond resolution. Have a look at the [time branch](https://github.com/twittner/tinylog/compare/time) and let me know if it would work for you.

**Comment by timbod7** [comment]
Hmm. I don't really want to see logs filled with 12 digits of second resolution. 3 digits (ie milliseconds) is what I'd like . Perhaps an alternative would be something like:

```
newtype DateFormat = DateFormat
    { formatf :: UTCTime -> Text
    }

instance IsString DateFormat where
    fromString fmt = DateFormat  . formatUnixTimeGMT (template fmt)
```

and then expose the `DateFormat` constructor so that a user has complete control over the format.

**Comment by twittner** [comment]
As in https://github.com/twittner/tinylog/compare/time-format-fn?

**Comment by timbod7** [comment]
Yes - that looks ideal.

**Comment by twittner** [comment]
Ok, I have merged this branch into `develop`. Will make a release soon.

**Comment by timbod7** [comment]
Great - thanks very much.

**Pull request closed without merging**
